# Path to top-level LLVM hierarchy
LEVEL=../../..

# Name of the library to build
LIBRARYNAME=StringLiteralWrite

# Make the shared library a loadable
# module so the tools can dlopen/dlsym
# to the resulting library.
LOADABLE_MODULE=1

# Include the LLVM common Makefile
include ${LEVEL}/Makefile.common
